/*
  A module to import into flakes based on flake-parts.
  Makes integration into a flake easy and tidy.
  See https://flake.parts,
*/

{ lib
, self
, flake-parts-lib
, ...
}:
let
  inherit (lib)
    mkOption
    types
    ;
in
{
  options = {
    perSystem = flake-parts-lib.mkPerSystemOption (
      { config
      , options
      , pkgs
      , ...
      }:
      let
        cfg = config.mcpix;
      in
      {
        options = {
          mcpix = {
            pkgs = mkOption {
              type = types.uniq (types.lazyAttrsOf (types.raw or types.unspecified));
              description = ''
                Nixpkgs to use in the mcpix.
              '';
              default = pkgs;
              defaultText = lib.literalMD "`pkgs` (module argument)";
            };
            settings = mkOption {
              type = types.submoduleWith {
                modules = [ ];
              };
              default = { };
              description = ''
                The mcpix configuration.
              '';
            };
            installationScript = mkOption {
              type = types.str;
              description = "A bash fragment that sets up mcpix.";
              default = cfg.settings.installationScript;
              defaultText = lib.literalMD "bash statements";
              readOnly = true;
            };
            devShell = mkOption {
              type = types.package;
              description = "A development shell that sets up files generated by mcpix.";
              readOnly = true;
            };
          };
        };
        config = {
          mcpix.settings =
            { pkgs, ... }:
            { };
          mcpix.devShell = pkgs.mkShell {
            shellHook = cfg.installationScript;
          };
        };
      }
    );
  };
}
