name: flake-check

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    flake-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5.0.0
            - name: Setup Nix environment
              uses: cachix/install-nix-action@v31
              with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up direnv
              uses: HatsuneMiku3939/direnv-action@v1.1.0
              with:
                direnvVersion: 2.37.1
            - run: nix build
            - run: nix flake check
